# Generated by Django 5.0.6 on 2024-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('user_since', models.DateTimeField(auto_now_add=True)),
                ('total_draw', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
