# Generated by Django 5.0.6 on 2024-06-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Draw date')),
                ('draw_count', models.IntegerField(default=0, verbose_name='Draw count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='poop.user')),
            ],
        ),
    ]
