# Generated by Django 5.0.6 on 2024-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poop', '0003_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
