# Generated by Django 5.0.6 on 2024-06-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poop', '0004_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.FilePathField()),
                ('total_draw', models.IntegerField(default=0)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='poop.user')),
                ('prompt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='poop.prompt')),
            ],
        ),
    ]
