# Generated by Django 5.0.6 on 2024-06-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poop', '0005_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('owned_since', models.DateTimeField(auto_now_add=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='poop.card')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='poop.user')),
            ],
        ),
    ]
