# Generated by Django 5.0.6 on 2024-06-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poop', '0006_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='prompt_id',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='user_id',
            new_name='user',
        ),
    ]
